# Generated by Django 3.2.13 on 2023-11-08 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='choleradatabase',
            name='cured',
            field=models.IntegerField(default=0),
        ),
    ]
