# Generated by Django 4.2.7 on 2023-12-11 09:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_district'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='choleradatabase',
            name='districts',
        ),
        migrations.AddField(
            model_name='choleradatabase',
            name='district',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.district'),
            preserve_default=False,
        ),
    ]
