# Generated by Django 4.2.7 on 2023-12-11 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_choleradatabase_districts_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='choleradatabase',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
